#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: 537da87
#
Name     : R-timechange
Version  : 0.3.0
Release  : 8
URL      : https://cran.r-project.org/src/contrib/timechange_0.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/timechange_0.3.0.tar.gz
Summary  : Efficient Manipulation of Date-Times
Group    : Development/Tools
License  : GPL-3.0
Requires: R-timechange-lib = %{version}-%{release}
Requires: R-cpp11
BuildRequires : R-cpp11
BuildRequires : buildreq-R

%description
accounting for time-zones and daylight saving times. The package includes
   utilities for updating of date-time components (year, month, day etc.),
   modification of time-zones, rounding of date-times, period addition and
   subtraction etc. Parts of the 'CCTZ' source code, released under the Apache
   2.0 License, are included in this package. See

%package lib
Summary: lib components for the R-timechange package.
Group: Libraries

%description lib
lib components for the R-timechange package.


%prep
%setup -q -n timechange
pushd ..
cp -a timechange buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1705588027

%install
export SOURCE_DATE_EPOCH=1705588027
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/timechange/DESCRIPTION
/usr/lib64/R/library/timechange/INDEX
/usr/lib64/R/library/timechange/Meta/Rd.rds
/usr/lib64/R/library/timechange/Meta/features.rds
/usr/lib64/R/library/timechange/Meta/hsearch.rds
/usr/lib64/R/library/timechange/Meta/links.rds
/usr/lib64/R/library/timechange/Meta/nsInfo.rds
/usr/lib64/R/library/timechange/Meta/package.rds
/usr/lib64/R/library/timechange/NAMESPACE
/usr/lib64/R/library/timechange/NEWS.md
/usr/lib64/R/library/timechange/R/timechange
/usr/lib64/R/library/timechange/R/timechange.rdb
/usr/lib64/R/library/timechange/R/timechange.rdx
/usr/lib64/R/library/timechange/help/AnIndex
/usr/lib64/R/library/timechange/help/aliases.rds
/usr/lib64/R/library/timechange/help/paths.rds
/usr/lib64/R/library/timechange/help/timechange.rdb
/usr/lib64/R/library/timechange/help/timechange.rdx
/usr/lib64/R/library/timechange/html/00Index.html
/usr/lib64/R/library/timechange/html/R.css
/usr/lib64/R/library/timechange/tests/testthat.R
/usr/lib64/R/library/timechange/tests/testthat/helpers.R
/usr/lib64/R/library/timechange/tests/testthat/test-addition.R
/usr/lib64/R/library/timechange/tests/testthat/test-get.R
/usr/lib64/R/library/timechange/tests/testthat/test-parse.R
/usr/lib64/R/library/timechange/tests/testthat/test-round.R
/usr/lib64/R/library/timechange/tests/testthat/test-time-zones.R
/usr/lib64/R/library/timechange/tests/testthat/test-update.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/timechange/libs/timechange.so
/usr/lib64/R/library/timechange/libs/timechange.so.avx2
/usr/lib64/R/library/timechange/libs/timechange.so.avx512
